spring:
  application:
    name: easyInvent
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: file:./src/main/resources/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/invent
    username: dbuser
    password: 12345
server:
  port: 8443
  servlet:
    context-path: /api/v1.0.0
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password










